### PR TITLE
Added Vox to the list.

### PR DESCRIPTION
**Pull request by hacknug**

### CODE REVIEW

**Comment by salomvary** [comment]
Too bad it crashes for me when trying to load SoundCloud :( https://gist.github.com/salomvary/ac5ec5e59f492bcd8cf6

**Comment by hacknug** [comment]
Are you using the Mac App Store version or the one from their site? The second works great for me on Yosemite.

**Comment by salomvary** [comment]
App Store one.

**Comment by salomvary** [comment]
Merged in 32f29b7de315b48b286a8d4b4a3c9036ebf56ab2

**Pull request closed without merging**
