### PR TITLE
Add touchbar support

### PR DESCRIPTION
**Pull request by kinglime**
Adds basic touchbar support featuring buttons for previous track, play/pause, next track, like and displays the title/artist.

touch bar shot 2017-03-12 at 4 40 11 pm

### CODE REVIEW

**Comment by salomvary** [comment]
I played around with it using the TouchBar simulator. Looks neat but has a couple of bugs:

- The status of play/pause button often gets out of sync when repeatedly used.
- The song title is not always shown (not sure how but I ended up with a song playing but no title displayed).

If you have the images in SVG format (or any other source format easier to modify) I would like to check them in with the code too (ideally generate the bitmaps from SVG as we do it with other images on the project).

**Comment by kinglime** [comment]
@salomvary not sure about the play/pause error. I tried to fix that by checking the isPlaying status.

I made the images myself by taking a screenshot of the iTunes touchbar and copying the elements. I'm not skilled enough to create the vector graphics unfortunately, that really isn't my forte.

Not sure about the song title either. I believe it gets it the same way the notification does. Does the notification display the title?

An a slightly unrelated note I was thinking about making the like button red, thoughts?

**Comment by salomvary** [comment]
> not sure about the play/pause error. I tried to fix that by checking the isPlaying status.

I have some ideas how to deal with this, will push or propose some code.

> I made the images myself by taking a screenshot of the iTunes touchbar and copying the elements. I'm not skilled enough to create the vector graphics unfortunately, that really isn't my forte.

Then I guess we will figure that out later, fine for now.

> An a slightly unrelated note I was thinking about making the like button red, thoughts?

Not sure, on the website red means stuff you already liked. Maintaining that state on the touchbar can be non-trivial. Let's keep it white:)

**Comment by kinglime** [comment]
Sounds good man. I'll test your code on my TouchBar when you update it.

**Comment by salomvary** [comment]
I added some improvements on this branch:
https://github.com/salomvary/soundcleod/tree/pr/140

Seems to be working smoother. The only bug I found and have not managed to fix is the track title sometimes disappearing. I suspect it depends on the title length and might be a bug in Electron or on Apple's side.

@kinglime would be nice if you could test my branch on a real TouchBar.

**Comment by kinglime** [comment]
@salomvary will test right now

**Comment by kinglime** [comment]
@salomvary couple things:

1. Not sure if I agree on the decision to remove the track title when paused. Wouldn't it make sense to keep it so they know what they're playing?

2. Everything works great on my end, didn't test it super thoroughly but it looks good. Let me know if there are any edge cases I should look out for.

3. I've determined that the info label can display a maximum of 38 characters. I suggest we first see if the track title + artist length is greater than 38 characters, if so we should remove the 'by artist' part. If the track title is still too long we could manually shorten it with string manipulation to keep it at a maximum of 38 characters. This way at least something is displayed rather than nothing.

That's all I've got, curious to hear what you think.

**Comment by salomvary** [comment]
> Not sure if I agree on the decision to remove the track title when paused. Wouldn't it make sense to keep it so they know what they're playing?

I agree title should stay on pause. Will change.

**Comment by kinglime** [comment]
@salomvary great. What are your thoughts on displaying the title in regards to its length?

**Comment by salomvary** [comment]
Filed a bug to Electron on the disappearing TouchBarLabel: https://github.com/electron/electron/issues/9009

Until that gets fixed, maybe just crop the title to some fixed number of characters, where the fixed number is something like the maximum number of 'W' characters that fit * 0.8.

**Comment by kinglime** [comment]
@salomvary I determined that we can fit 38 characters.

**Comment by salomvary** [comment]
Landed everything on master, will release SoundCleod once Electron with TouchBar support gets released ([it's still in beta](https://github.com/electron/electron/releases)).

**Pull request merged**
