### PR TITLE
WIP: deps: bump to Electron 7.x

### PR DESCRIPTION
**Pull request by jbergstroem**
~Note: this is a wip since tests aren't passing.~

Tests passes for me locally now. Did some other minor fixes.

Refs: #193

### CODE REVIEW

**Comment by jbergstroem** [comment]
Ok, enough messing around. Electron is at 7 now and works locally. Not sure why ci is unhappy so that'd be the next step..

**Comment by jbergstroem** [comment]
#### Travis
`npm ci` fails and I can reproduce locally. Seems relatively easy to solve

#### Appveyor
A timeout (1h) for the job, likely some trial and error with tweaking electron for "ci use".

**Comment by bpollman** [comment]
@jbergstroem This is awesome. Thanks for working to update the app. I tried out your branch and it seems to run alot better with the electron updates. 

Did a quick look at the test failures too...The facebook tests look like they can just be removed as soundcloud doesnt offer FB login anymore. Not sure about the other failures though, I've never messed with electron apps before. 

@salomvary Hope you accept this PR and get a new release out soon!

**Comment by salomvary** [comment]
@joelekstrom Thanks for the work keeping things updated! I will have a look and get this merged. Can't promise a release too quick, I have some burdens to tackle regarding code signing before.

> soundcloud doesnt offer FB login anymore

@bpollman doesn't look like it:
Screenshot 2019-10-25 at 08 34 25

Having said that, some of the tests have been quite a pain to maintain, I'm up for removing them if they are not easy to fix. Upgrading Spectron (the test runner) might help, but my experience with this framework has not been great.

**Comment by salomvary** [comment]
Thanks, merged! Will fix the remaining test issues on master.

**Comment by jbergstroem** [comment]
> Did a quick look at the test failures too...The facebook tests look like they can just be removed as soundcloud doesnt offer FB login anymore. Not sure about the other failures though, I've never messed with electron apps before.

I think there's some user-agent check going on. I see it in browser but not in app.

**Comment by salomvary** [comment]
> I see it in browser but not in app.

That was due to this dirty hack no longer working: 6dcef70a0b1faf03c61784708520e1e621a40525

**Comment by salomvary** [comment]
...but I managed to fix the tests on `master` \o/

**Comment by jbergstroem** [comment]
> ...but I managed to fix the tests on master \o/

Great!

**Comment by bpollman** [comment]
ah i see! Awesome to see it moving along

**Pull request merged**
