### PR TITLE
Add a like/dislike option

### PR DESCRIPTION
**Pull request by kinglime**
Adds a "like/dislike" option to the dock and menu bar. This allows the user to like and or dislike the currently playing song without opening the application.

### CODE REVIEW

**Comment by salomvary** [comment]
SoundCloud uses the word "unlike" to "undo" a like, what do you think about changing to that?

As SoundCloud itself also binds to the "L" shortcut does this not create two like "clicks" when the application is focused?

Nice feature otherwise!

**Comment by kinglime** [comment]
You're right, unlike makes more sense than "dislike", not sure what I was thinking ha ha. I will go ahead and make the necessary changes. I'll have to see about the L shortcut. I didn't think to test that. Assuming it is problematic what do you think would be an appropriate alternative?

**Comment by kinglime** [comment]
@salomvary So I've switched it to Like/Unlike everywhere in the code. I've noticed a bug with the menu however. When you just click the like option it works fine. It appears that no combo of key shortcuts works however. The shortcuts call the proper function in Soundcloud.js but the keypress doesn't seem to fire? Perhaps you could help me look into this

**Comment by salomvary** [comment]
Oops, I already merged your (slightly tweaked) changes in 47c9081a77d6ae9d658a5726a44ce687aa3ccace sorry for not updating here.

**Comment by salomvary** [comment]
I did not see any issues with the keyboard shortcut.

**Comment by salomvary** [comment]
Closing here, changes will be released soon(ish).

**Comment by kinglime** [comment]
Hmm OK so the shortcut worked on your end? That is odd.

**Pull request closed without merging**
