### PR TITLE
Added bluetooth headphone Play/Pause

### PR DESCRIPTION
**Pull request by jugendhacker**
I found a solution for the problem.

### CODE REVIEW

**Comment by salomvary** [comment]
Hey, thanks for the fix! Tweaked it in a4939f3e3c184bb130de761869fc4dcc11a4141e a little bit so that it never starts playback if you press the pause button and works for people with a single play/pause button too.

Could you please test again it on the latest master to make sure my tweaks did not break anything?

**Comment by jugendhacker** [comment]
Ok the problem now is that the songs didn't load why?

**Comment by salomvary** [comment]
> Ok the problem now is that the songs didn't load why?

Not sure, things should work. Do you see anything weird on the terminal where you run `npm start`? Anything in the developer tools console (View menu -> Developer tools)?

**Comment by jugendhacker** [comment]
I only get this in the developer tools:

> app-dd5253a-2272b4f-3.js:29 You like to look under the hood? Why not help us build the engine? https://soundcloud.com/jobs
promoted.soundcloud.com/event?z=dashbox-stream&e=SCImpression&a=599970018-127575031458&c=37970328744986&g=DE&t=1517239166618&q=visual Failed to load resource: the server responded with a status of 400 (Bad Request)
avatars-000375896570-4es181-t20x20.jpg Failed to load resource: the server responded with a status of 404 ()
avatars-000388533735-rmgd12-t20x20.jpg Failed to load resource: the server responded with a status of 404 ()

**Comment by salomvary** [comment]
Then I have no idea, afraid it might be something specific to your setup :( Things seem to be working fine for me on master, will release a new version with the fix soon(ish).

**Comment by jugendhacker** [comment]
Ok I will test it with the new release...

**Comment by jugendhacker** [comment]
I think I can close this because you merged my changes!

**Pull request closed without merging**
