### PR TITLE
 Added simple regex for testing if base url is a soundcloud.com site

### PR DESCRIPTION
**Pull request by jugendhacker**
I added a regex that tests if the --base-url flag is a soundcloud url!

### CODE REVIEW

**Comment by salomvary** [comment]
Hey, thanks for the effort however this does not have the intended effect. I assume this is meant to implement the SoundCloud URL launch argument discussed in #164, while `--base-url` has a different purpose (see my reply there).

Furthermore regexes are almost never the right way to process URLs, I would suggest using [`URL.parse`](https://nodejs.org/docs/latest/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost).

**Comment by jugendhacker** [comment]
Why not regex?

**Comment by salomvary** [comment]
> Why not regex?

Even short regexes tend to be hard to read, therefore hard to spot bugs or make changes to. This one for example is simple enough still has at least one bug (can you spot it?).

I would suggest something like this:

 ```js
const url = require('url')
const {protocol, hostname} = url.parse(baseUrl)
 if ((protocol === 'https' || protocol === 'http') && hostname === 'soundcloud.com') {
   // It is a SoundCloud link
}
```

Fun fact: you can find a couple of existing "url parsing the wrong way" examples in this codeabase. One of them does exactly the same (verifies a soundcloud.com URL), the other one has a similar bug to the one here;)

**Comment by jugendhacker** [comment]
So I would remove my regex thing from the base url and add this non flag argument ok?

**Comment by jugendhacker** [comment]
Now I tried to add it! Please look at it!

**Comment by salomvary** [comment]
Implemented slightly differently on master, to be released soon.

**Pull request closed without merging**
